web:
  build: .
  dockerfile: Dockerfile-development
  ports:
   - "8080:8080"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: development
   PORT: 8080
   SPARKPOST_KEY: ${SPARKPOST_KEY}
