web:
  build: .
  ports:
   - "8080:8080"
  restart: always
  environment:
   NODE_ENV: production
   PORT: 8080
   SPARKPOST_KEY: ${SPARKPOST_KEY}

storybook:
  build: .
  ports:
   - "9001:9001"
  restart: always
  environment:
   NODE_ENV: development
