version: 2
jobs:
  build:
    branches:
      only: master
    working_directory: ~/app
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: yarn
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: yarn relay && yarn build && yarn build:server

      - run:
          name: lint
          command: yarn lint

      - run:
          name: deploy
          command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'cd /opt/chrisdriscol && eval `ssh-agent -s` && ssh-add ~/.ssh/github_rsa && git fetch origin && git reset --hard origin/master && docker-compose up --build -d'


